### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by mistune** [lucasvanmol/obsidian-latex-ocr#16]
I keep getting error 400 with the Inference API. I would be happy to provide logs from my machine if needed.

**Comment by lucasvanmol** [comment]
Hey, thanks for raising this issue.

If you could share, I'd love to see

- logs 
- your OS
- the plugin version

Thank you!

**Comment by ZeroCommits** [comment]
Hello @lucasvanmol, can you share how to extract logs just after pasting an image? Here are the other details:

OS: Debian 12
Plugin version: 0.6.4

**Comment by lucasvanmol** [comment]
This is might be related to some issues on Linux where file paths aren't being read properly. I'm going to investigate on a VM to see if I can replicate it, thanks

**Comment by TheTomato18** [comment]
Hi having the same issues

OS: Windows 11
Plugin verson: 0.6.4

**Comment by lucasvanmol** [comment]
Hi, could you please try and see if the newest version `0.6.5` has fixed this for you?

**Comment by TheTomato18** [comment]
`0.6.5` has fixed this issue for me!

**Comment by mistune** [comment]
`0.6.5` also fixed the issue for me. Thanks @lucasvanmol
