### ISSUE TITLE
Conda Environment Installation

### ISSUE THREAD

**Issue by lstoex** [lucasvanmol/obsidian-latex-ocr#20]
Hey I am having troubles with a conda env for the server.
I have changed the path in the plugin settings to the corresponding interpreter path but it says the server isn't installed.
Also it doesn't save the settings for the path. When I change the settings tab and come back, it reverted to the vanilla python3 path.
Have you experienced anything like this before ?

Works all fine when I start the server manually in a shell. Thanks for this great project!

**Comment by lucasvanmol** [comment]
Hi there, unfortunately I'm not very familiar with conda environments. 

When you start the server manually, are you able to start it from the interpreter in the conda env? For example are you able to run: 
```
/path/to/your/Anaconda/Scripts/python.exe -m latex_ocr_server --version
```

**Comment by lstoex** [comment]
Works fine!
Btw im running Obsidian on Linux (Ubuntu)
