### ISSUE TITLE
Remove unnecessary logs in console

### ISSUE THREAD

**Issue by KrazyManJ** [lucasvanmol/obsidian-latex-ocr#26]
Hello, as a developer, while working on obsidian enhancing, I usually have console opened. This plugin every 5 seconds sends text with ocr server status into console and it interrupts my workflow. I know that i can hide it via filter using `-url:plugin:latex-ocr` but I have to do it everytime I open console.

Could you remove these logs or add at least option in console to disable them please? (like debug mode, when on, these logs will appear in console).

**Comment by lucasvanmol** [comment]
This was something on my radar but I never got around to doing it, thanks for the reminder! Hopefully the 0.7.4 update is better for you.

**Comment by KrazyManJ** [comment]
@lucasvanmol , thank you for your response and quick update, I appreciate it a a lot. It does not spam console anymore so this issue is solved. Your plugin does it's job and I like it!
