### ISSUE TITLE
[BUG]: Fails to load on 1.7.4

### ISSUE THREAD

**Issue by xRyul** [lucasvanmol/obsidian-latex-ocr#28]
This plugin is awesome! Saves loads of time during lectures! While everyone is still writing out their formulas, I am already annotating how it works! It is grreat, however it seems to fail after the latest Obsidian update v1.7.4:

![image](https://github.com/user-attachments/assets/e2c4b2c4-349d-44c7-8c68-c7f20505fa36)

**Comment by lucasvanmol** [comment]
Hi there, thanks for raising this issue!

What model are you trying to use? The huggingface API or locally? Was it running fine before 1.7.4?

**Comment by xRyul** [comment]
HuggingFace API. 

It used to work fine before Obsidian update. 

Now it wont let me even load the settings. 

![image](https://github.com/user-attachments/assets/6f74f9e1-2dc3-4718-bf66-c225019466b7)

![image](https://github.com/user-attachments/assets/ad0bbb3e-d9b3-421f-99c3-6c2e454f1eb1)

**Comment by lucasvanmol** [comment]
It seems like the API key is malformed somehow... I'll be able to fix it so it doesn't crash on start up, but for now could you try uninstalling the plugin and redownloading it? Make sure the plugin folder is deleted fully, Obsidian is sometimes weird about this but if the plugin folder is gone you should be good to reinstall. You'll then have to put in your API key in again.

**Comment by xRyul** [comment]
> It seems like the API key is malformed somehow... I'll be able to fix it so it doesn't crash on start up, but for now could you try uninstalling the plugin and redownloading it? Make sure the plugin folder is deleted fully, Obsidian is sometimes weird about this but if the plugin folder is gone you should be good to reinstall. You'll then have to put in your API key in again.

This is actually embarrassing. But reinstalling the plugin actually fixed it! Many thanks!
