### ISSUE TITLE
[BUG] "Python path" setting does not persist if set through file picker

### ISSUE THREAD

**Issue by SubsequentlySneeds** [lucasvanmol/obsidian-latex-ocr#31]
**Describe the bug**
When using a local model, attempting to locate Python through the file picker replaces the text with the new path, but it is cleared and replaced with the previous value after closing and reopening settings.

**To Reproduce**
1. Go to "Latex OCR" settings
2. Click on the file picker in "Python path"
3. Choose a different location from the existing value
4. Close settings
5. Reopen settings to see the previous value (attempting to start the server does not use the file-picker value even if settings is not reopened)

**Environment**
I am on:
- [ ] MacOS
- [x] Windows
- [ ] Linux

Using the model:
- [x] Local model with python
- [ ] Inference API with Huggingface

**Comment by lucasvanmol** [comment]
Thanks for the fix!
