### ISSUE TITLE
Local Model configuration options not appearing

### ISSUE THREAD

**Issue by RemiMak** [lucasvanmol/obsidian-latex-ocr#8]
![image](https://github.com/lucasvanmol/obsidian-latex-ocr/assets/91879096/99cb61a6-0247-47b3-ab4a-8db69a0b8cc0)

I installed the plugin manually, installed the Python package, and checked whether it was correctly installed (`python -m latex_ocr_server --version` works like it should).

**Comment by lucasvanmol** [comment]
Hi, thanks for raising this issue, please try updating to 0.4.2!

**Comment by RemiMak** [comment]
Hey there, I just updated and the model finished loading. It works like a charm! Thanks for the hard work! 🥳
